version: '3.8'

services:
  # Serviço do RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=hyper_user
      - RABBITMQ_DEFAULT_PASS=hyper_password
    networks:
      - hyperativa-net

  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hyperativa_db
      - MYSQL_USER=hyper_user
      - MYSQL_PASSWORD=hyper_password
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - hyperativa-net

  # Serviço da API Principal
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hyperativa_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=hyper_user
      - SPRING_DATASOURCE_PASSWORD=hyper_password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=hyper_user
      - SPRING_RABBITMQ_PASSWORD=hyper_password
      - JWT_SECRET=ZDA2NDMyNDAtYzlkNS00MzY2LTg1ODEtZDc3NDQ3Y2VhMjBh
      - JWT_EXPIRATION_MS=600000
      - ENCRYPTION_AES_SECRET-KEY=KVQcNxRLaSI0LmvtgXx5AH+9VOIARMMk3o34QLSSFNE=
      - HYPERATIVA_RABBITMQ_QUEUE=cards.queue
      - HYPERATIVA_RABBITMQ_EXCHANGE=cards.exchange
      - HYPERATIVA_RABBITMQ_ROUTINGKEY=cards.routingkey
    depends_on:
      - db
      - rabbitmq
    networks:
      - hyperativa-net

  # Serviço do Consumer de Cartões
  card-consumer:
    build:
      context: ./card-consumer
      dockerfile: Dockerfile
    container_name: card-consumer-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hyperativa_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=hyper_user
      - SPRING_DATASOURCE_PASSWORD=hyper_password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=hyper_user
      - SPRING_RABBITMQ_PASSWORD=hyper_password
      - ENCRYPTION_AES_SECRET-KEY=KVQcNxRLaSI0LmvtgXx5AH+9VOIARMMk3o34QLSSFNE=
      - HYPERATIVA_RABBITMQ_QUEUE=cards.queue
    depends_on:
      - db
      - rabbitmq
    networks:
      - hyperativa-net

networks:
  hyperativa-net:
    driver: bridge
    