server:
  port: 8080
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: hyperativa-api

spring:
  application:
    name: api
  profiles:
    active: local
  rabbitmq:
    admin:
      auto-startup: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html