spring:
  application:
    name: card-consumer
    # Configuração do Banco de Dados
    datasource:
      url: jdbc:mysql://localhost:3306/hyperativa_db
      username: hyperativa_ms_app_user
      password: HyperativaMSQL@2025
      driver-class-name: com.mysql.cj.jdbc.Driver

    # Configuração do JPA/Hibernate
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

    # Configuração do RabbitMQ
    rabbitmq:
      host: localhost
      port: 5672
      username: hyperativa
      password: rabbit@hyperativa

# Propriedades customizadas
encryption:
  aes:
    secret-key: NDBGNTI2NzUzODcyNDEzRjQ0Mjg0NzJiNTA2NDUzNjc1NjZiNTk3MA==

hyperativa:
  rabbitmq:
    queue: cards.queue