spring:
  application:
    name: card-consumer
  # Configuração do Banco de Dados
  datasource:
    url: jdbc:mysql://localhost:3306/hyperativa_db
    username: ${your_user}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  # Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: ${your_user}
    password: ${your_password}

# Propriedades customizadas
encryption:
  aes:
    secret-key: ARiaCTRO1v2rYH8lX+aBS0AoBGiZ6v3+QatdbtY49r4= # Chave AES para ambiente local

hyperativa:
  rabbitmq:
    queue: cards.queue
    dlq: cards.queue.dlq
    exchange-dlx: cards.exchange.dlx