server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: https://github.com/Hachibitz/hyperativa-backend-challenge-configs
          default-label: main
          username: ${TOKEN}
          password: ${TOKEN}
          force-pull: true
          clone-on-start: true